
name : Different OSs
on : [ push ]

jobs :

  windows-2016 :
    strategy :
      fail-fast : false
      matrix :
        os : [ windows-2016 ]
        node-version : [ 12.x, 14.x, 16.x ]
    runs-on : ${{ matrix.os }}
    steps :
    - name : ${{ matrix.node-version }}
      uses : actions/setup-node@v1
      with :
        node-version : ${{ matrix.node-version }}
    - run : npm install wdeasync@gamma w.process.tree.windows@gamma bufferfromfile@gamma

  windows-2019 :
    strategy :
      fail-fast : false
      matrix :
        os : [ windows-2019 ]
        node-version : [ 12.x, 14.x, 16.x ]
    runs-on : ${{ matrix.os }}
    steps :
    - name : ${{ matrix.node-version }}
      uses : actions/setup-node@v1
      with :
        node-version : ${{ matrix.node-version }}
    - run : npm install wdeasync@gamma w.process.tree.windows@gamma bufferfromfile@gamma

  windows-2022 :
    strategy :
      fail-fast : false
      matrix :
        os : [ windows-2022 ]
        node-version : [ 12.x, 14.x, 16.x ]
    runs-on : ${{ matrix.os }}
    steps :
    - name : ${{ matrix.node-version }}
      uses : actions/setup-node@v1
      with :
        node-version : ${{ matrix.node-version }}
    - run : npm install wdeasync@gamma w.process.tree.windows@gamma bufferfromfile@gamma
