
name : Two modules
on : [ push ]

jobs :

  deasync-wprocess-tree :
    strategy :
      fail-fast : false
      matrix :
        os : [ windows-2019 ]
        node-version : [ 12.x, 14.x, 16.x ]
    runs-on : ${{ matrix.os }}
    steps :
    - name : ${{ matrix.node-version }}
      uses : actions/setup-node@v1
      with :
        node-version : ${{ matrix.node-version }}
    - run : npm install wdeasync@gamma w.process.tree.windows@gamma

  deasync-bufferfromfile :
    strategy :
      fail-fast : false
      matrix :
        os : [ windows-2019 ]
        node-version : [ 12.x, 14.x, 16.x ]
    runs-on : ${{ matrix.os }}
    steps :
    - name : ${{ matrix.node-version }}
      uses : actions/setup-node@v1
      with :
        node-version : ${{ matrix.node-version }}
    - run : npm install wdeasync@gamma bufferfromfile@gamma

  bufferfromfile-wprocess-tree :
    strategy :
      fail-fast : false
      matrix :
        os : [ windows-2019 ]
        node-version : [ 12.x, 14.x, 16.x ]
    runs-on : ${{ matrix.os }}
    steps :
    - name : ${{ matrix.node-version }}
      uses : actions/setup-node@v1
      with :
        node-version : ${{ matrix.node-version }}
    - run : npm install bufferfromfile@gamma w.process.tree.windows@gamma
